markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

title: Collin Turney
email: 
description: family, tinkering, and oxford commas
baseurl: ""
url: "https://collinturney.github.io"
github_username: collinturney
google_analytics: UA-97199993-1
