markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

title: family, tinkering, and oxford commas
email: 
description:
baseurl: ""
url: "https://collinturney.github.io"
github_username: collinturney
