title: Collin Turney
email: collinturney[at]gmail
description: family, tinkering, and oxford commas
baseurl: ""
url: "https://collinturney.github.io"
markdown: kramdown

github_username: collinturney
resume_url: https://www.visualcv.com/collinturney
