title: Collin Turney
email: collinturney[at]gmail
description: family, tinkering, and oxford commas
baseurl: ""
url: "https://collinturney.github.io"
github_username: collinturney

markdown: kramdown
